// Essence Yogurt - Email Backup Service 2026
// Sends: QA reports, backup confirmations, deploy summaries,
// error logs, incident escalations.
// Target: support@essenceyogurt.com

import nodemailer from "nodemailer";
import os from "os";

export interface EmailPayload {
  subject: string;
  html: string;
  attachments?: Array<{ filename: string; content: Buffer | string }>;
}

export class EssenceEmailService {
  private transporter: nodemailer.Transporter | null = null;
  private sender: string;
  private recipient: string;
  private isConfigured: boolean;

  constructor() {
    this.sender = process.env.ESN_SMTP_EMAIL || "noreply@essenceyogurt.com";
    this.recipient = process.env.ESN_SUPPORT_EMAIL || "support@essenceyogurt.com";
    
    const smtpEmail = process.env.ESN_SMTP_EMAIL;
    const smtpPass = process.env.ESN_SMTP_PASS;
    
    this.isConfigured = Boolean(smtpEmail && smtpPass);
    
    if (this.isConfigured) {
      this.transporter = nodemailer.createTransport({
        host: "smtp.gmail.com",
        port: 465,
        secure: true,
        auth: {
          user: smtpEmail,
          pass: smtpPass,
        },
      });
    }
  }

  async send(payload: EmailPayload): Promise<{ ok: boolean; error?: string }> {
    if (!this.isConfigured || !this.transporter) {
      console.log("[EssenceEmailService] Email not configured - would send:", payload.subject);
      return { ok: true, error: "Email service not configured (simulated send)" };
    }
    
    try {
      await this.transporter.sendMail({
        from: `"Essence Yogurt – AI Core" <${this.sender}>`,
        to: this.recipient,
        subject: payload.subject,
        html: payload.html,
        attachments: payload.attachments,
      });
      console.log("[EssenceEmailService] Email sent:", payload.subject);
      return { ok: true };
    } catch (err: any) {
      console.error("[EssenceEmailService Error]", err);
      return { ok: false, error: String(err) };
    }
  }
  
  getStatus(): { configured: boolean; recipient: string } {
    return { configured: this.isConfigured, recipient: this.recipient };
  }
}

// Singleton instance
let emailService: EssenceEmailService | null = null;

export function getEmailService(): EssenceEmailService {
  if (!emailService) {
    emailService = new EssenceEmailService();
  }
  return emailService;
}

// Daily digest queue to avoid spam
let digestStore: string[] = [];

export function queueDigestMessage(text: string): void {
  digestStore.push(`[${new Date().toISOString()}] ${text}`);
}

export function getDigestQueue(): string[] {
  return [...digestStore];
}

// Called once every day by scheduler
export async function sendDailyDigest(): Promise<{ ok: boolean; messageCount: number }> {
  const count = digestStore.length;
  
  if (count === 0) {
    return { ok: true, messageCount: 0 };
  }

  const email = getEmailService();
  const combined = digestStore.join("<br>");

  const result = await email.send({
    subject: "Daily Essence Yogurt System Digest – Octopus Brain 2026",
    html: `
      <div style="font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: linear-gradient(135deg, #B08D57, #D6A743); padding: 20px; text-align: center;">
          <h1 style="color: white; margin: 0;">Essence Yogurt</h1>
          <p style="color: white; margin: 5px 0 0;">Daily System Digest</p>
        </div>
        <div style="padding: 20px; background: white;">
          <p>Automatically generated by Octopus Brain 2026.</p>
          <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
          ${combined}
          <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
          <p style="color: #666; font-size: 12px;">Host: ${os.hostname()}</p>
          <p style="color: #666; font-size: 12px;">Generated: ${new Date().toISOString()}</p>
        </div>
      </div>
    `,
  });

  if (result.ok) {
    console.log(`[EssenceEmailService] Daily digest sent with ${count} messages`);
    digestStore = [];
  }
  
  return { ok: result.ok, messageCount: count };
}

// Backup notification
export async function notifyBackupComplete(backupInfo: {
  sizeMB: number;
  fileName: string;
  createdAt: string;
  destination?: string;
  fileCount?: number;
  dbRecords?: number;
}): Promise<{ ok: boolean }> {
  const email = getEmailService();

  const html = `
    <div style="font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background: linear-gradient(135deg, #B08D57, #D6A743); padding: 20px; text-align: center;">
        <h1 style="color: white; margin: 0;">Essence Yogurt</h1>
        <p style="color: white; margin: 5px 0 0;">Backup Notification</p>
      </div>
      <div style="padding: 20px; background: white;">
        <h2 style="color: #1a1a1a;">Backup Completed Successfully</h2>
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>File:</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #eee;">${backupInfo.fileName}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>Size:</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #eee;">${backupInfo.sizeMB} MB</td>
          </tr>
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>Created:</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #eee;">${backupInfo.createdAt}</td>
          </tr>
          ${backupInfo.destination ? `
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>Destination:</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #eee;">${backupInfo.destination}</td>
          </tr>
          ` : ''}
        </table>
        <p style="color: #28a745; margin-top: 20px;">All systems are functioning normally.</p>
      </div>
    </div>
  `;

  return email.send({
    subject: "Essence Yogurt — Backup Completed" + (backupInfo.destination ? ` (${backupInfo.destination})` : ''),
    html,
  });
}

// Error notification
export async function notifyError(error: any, context?: string): Promise<{ ok: boolean }> {
  const email = getEmailService();

  const html = `
    <div style="font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background: #dc3545; padding: 20px; text-align: center;">
        <h1 style="color: white; margin: 0;">Essence Yogurt</h1>
        <p style="color: white; margin: 5px 0 0;">ERROR ALERT</p>
      </div>
      <div style="padding: 20px; background: white;">
        <h2 style="color: #dc3545;">Critical Backend Error</h2>
        ${context ? `<p><strong>Context:</strong> ${context}</p>` : ""}
        <pre style="background: #f8f9fa; padding: 15px; border-radius: 5px; overflow-x: auto;">${String(error)}</pre>
        <p style="color: #666;">Automatic QA will continue. Manual review may be required.</p>
        <p style="color: #666; font-size: 12px;">Host: ${os.hostname()}</p>
        <p style="color: #666; font-size: 12px;">Time: ${new Date().toISOString()}</p>
      </div>
    </div>
  `;

  return email.send({
    subject: "Essence Yogurt – ERROR ALERT",
    html,
  });
}

// Deploy notification
export async function notifyDeploy(info: {
  version: string;
  env: string;
  url: string;
}): Promise<{ ok: boolean }> {
  const email = getEmailService();

  const html = `
    <div style="font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background: linear-gradient(135deg, #B08D57, #D6A743); padding: 20px; text-align: center;">
        <h1 style="color: white; margin: 0;">Essence Yogurt</h1>
        <p style="color: white; margin: 5px 0 0;">Deployment Notification</p>
      </div>
      <div style="padding: 20px; background: white;">
        <h2 style="color: #28a745;">Deployment Completed Successfully</h2>
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>Version:</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #eee;">${info.version}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>Environment:</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #eee;">${info.env}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>URL:</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #eee;"><a href="${info.url}">${info.url}</a></td>
          </tr>
        </table>
        <p style="color: #666; margin-top: 20px;">Octopus Brain 2026 is now live.</p>
      </div>
    </div>
  `;

  return email.send({
    subject: `Deployed Successfully – Version ${info.version}`,
    html,
  });
}

// Incident escalation
export async function notifyIncidentEscalation(incident: {
  id: string;
  shopId: string;
  title: string;
  severity: string;
  aiSummary: string;
}): Promise<{ ok: boolean }> {
  const email = getEmailService();

  const severityColors: Record<string, string> = {
    CRITICAL: "#dc3545",
    HIGH: "#fd7e14",
    MEDIUM: "#ffc107",
    LOW: "#28a745",
  };

  const severityColor = severityColors[incident.severity] || "#666";

  const html = `
    <div style="font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background: ${severityColor}; padding: 20px; text-align: center;">
        <h1 style="color: white; margin: 0;">Essence Yogurt</h1>
        <p style="color: white; margin: 5px 0 0;">INCIDENT ESCALATION</p>
      </div>
      <div style="padding: 20px; background: white;">
        <h2 style="color: #1a1a1a;">Incident Requires Immediate Attention</h2>
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>ID:</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #eee;">${incident.id}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>Shop:</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #eee;">${incident.shopId}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>Title:</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #eee;">${incident.title}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>Severity:</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #eee;">
              <span style="background: ${severityColor}; color: white; padding: 2px 8px; border-radius: 3px;">${incident.severity}</span>
            </td>
          </tr>
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>AI Summary:</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #eee;">${incident.aiSummary}</td>
          </tr>
        </table>
        <p style="color: #dc3545; font-weight: bold; margin-top: 20px;">HQ immediate review required.</p>
        <p style="color: #666; font-size: 12px;">Time: ${new Date().toISOString()}</p>
      </div>
    </div>
  `;

  return email.send({
    subject: `Incident Escalation – ${incident.severity} – ${incident.id}`,
    html,
  });
}

// QA Report notification
export async function notifyQAReport(report: {
  testsPassed: number;
  testsFailed: number;
  coverage?: number;
  summary: string;
}): Promise<{ ok: boolean }> {
  const email = getEmailService();
  const allPassed = report.testsFailed === 0;

  const html = `
    <div style="font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background: ${allPassed ? "#28a745" : "#dc3545"}; padding: 20px; text-align: center;">
        <h1 style="color: white; margin: 0;">Essence Yogurt</h1>
        <p style="color: white; margin: 5px 0 0;">QA Report</p>
      </div>
      <div style="padding: 20px; background: white;">
        <h2 style="color: ${allPassed ? "#28a745" : "#dc3545"};">
          ${allPassed ? "All Tests Passed" : "Some Tests Failed"}
        </h2>
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>Passed:</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #eee; color: #28a745;">${report.testsPassed}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>Failed:</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #eee; color: ${report.testsFailed > 0 ? "#dc3545" : "#28a745"};">${report.testsFailed}</td>
          </tr>
          ${report.coverage !== undefined ? `
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>Coverage:</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #eee;">${report.coverage}%</td>
          </tr>
          ` : ""}
        </table>
        <h3 style="margin-top: 20px;">Summary</h3>
        <p>${report.summary}</p>
        <p style="color: #666; font-size: 12px;">Generated: ${new Date().toISOString()}</p>
      </div>
    </div>
  `;

  return email.send({
    subject: `QA Report – ${allPassed ? "PASSED" : "FAILED"} – ${report.testsPassed}/${report.testsPassed + report.testsFailed}`,
    html,
  });
}
